#!/bin/sh
{
  echo SERVER_URL="$SERVER_URL";
  echo SERVER_PORT="$PORT";
  echo LOG_LEVEL="$LOG_LEVEL";
  echo CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS";
  echo AUTH_SALT_ROUNDS="$AUTH_SALT_ROUNDS";
  echo AUTH_JWT_SCHEME="$AUTH_JWT_SCHEME";
  echo AUTH_JWT_SECRET="$AUTH_JWT_SECRET";
  echo AUTH_JWT_ISSUER="$AUTH_JWT_ISSUER";
  echo EMAIL_SENDER_NAME="$EMAIL_SENDER_NAME";
  echo EMAIL_SENDER_ADDRESS="$EMAIL_SENDER_ADDRESS";
  if [ "$EMAIL_PROVIDER" != "ses" ]; then
    echo EMAIL_USER="$EMAIL_USER";
    echo EMAIL_PASSWORD="$EMAIL_PASSWORD";
    echo EMAIL_HOST="$EMAIL_HOST";
    echo EMAIL_PORT="$EMAIL_PORT";
  fi
  echo STORAGE_PROVIDER="$STORAGE_PROVIDER";
  echo STORAGE_PATH="$STORAGE_PATH";
  if [ "$STORAGE_PROVIDER" = "amazon" ]; then
    echo STORAGE_KEY="$AWS_ACCESS_KEY";
    echo STORAGE_SECRET="$AWS_ACCESS_SECRET";
    echo STORAGE_REGION="$AWS_REGION";
    echo STORAGE_BUCKET="$S3_STORAGE_BUCKET";
  fi
  echo PUBLISHED_CONTENT="$PUBLISHED_CONTENT";
  echo IMPORTED_CONTENT="$IMPORTED_CONTENT";
  echo DATABASE_NAME="$DATABASE_NAME";
  echo DATABASE_USER="$DATABASE_USER";
  echo DATABASE_PASSWORD="$DATABASE_PASSWORD";
  echo IMPORT_TEMPLATE_FORMAT="$IMPORT_TEMPLATE_FORMAT";
} >> .env
