#!/bin/sh
{
  echo SERVER_URL="$SERVER_URL";
  echo PORT="$PORT";
  echo LOG_LEVEL="$LOG_LEVEL";
  echo CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS";
  echo AUTH_SALT_ROUNDS="$AUTH_SALT_ROUNDS";
  echo AUTH_JWT_SCHEME="$AUTH_JWT_SCHEME";
  echo AUTH_JWT_SECRET="$AUTH_JWT_SECRET";
  echo AUTH_JWT_ISSUER="$AUTH_JWT_ISSUER";
  echo EMAIL_PROVIDER="$EMAIL_PROVIDER";
  echo EMAIL_SENDER_NAME="$EMAIL_SENDER_NAME";
  echo EMAIL_SENDER_ADDRESS="$EMAIL_SENDER_ADDRESS";
  echo EMAIL_USER="$EMAIL_USER";
  echo EMAIL_PASSWORD="$EMAIL_PASSWORD";
  echo EMAIL_HOST="$EMAIL_HOST";
  echo EMAIL_PORT="$EMAIL_PORT";
  echo STORAGE_PROVIDER="$STORAGE_PROVIDER";
  echo STORAGE_PATH="$STORAGE_PATH";
  echo PUBLISHED_CONTENT="$PUBLISHED_CONTENT";
  echo IMPORTED_CONTENT="$IMPORTED_CONTENT";
  echo DATABASE_HOST="$DATABASE_HOST";
  echo DATABASE_PORT="$DATABASE_PORT";
  echo DATABASE_NAME="$DATABASE_NAME";
  echo DATABASE_USER="$DATABASE_USER";
  echo DATABASE_PASSWORD="$DATABASE_PASSWORD";
  echo IMPORT_TEMPLATE_FORMAT="$IMPORT_TEMPLATE_FORMAT";
} >> .env
